version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: jobapp-postgres
    environment:
      POSTGRES_DB: jobapp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lasBr01
    ports:
      - "5432:5432"
    networks:
      - jobapp-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: jobapp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    networks:
      - jobapp-network
    depends_on:
      - postgres

networks:
  jobapp-network:
